/* Even Fibonacci numbers */
/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

var sum =0;
function fibNac(n1, n2){
  var fib = 0
  fib = n1 + n2;
  n1 = n2;
  n2 = fib;
  if(fib< 4e6){
    if(fib % 2 == 0)
      sum += fib;
    fibNac(n1, n2);
  }
  else{
    console.log("Sum is" + sum);
    return;
  }
}

fibNac(0,1);